declare-option str t1 'rgb:101719'
declare-option str t2 'rgb:1B2A32'
declare-option str t3 'rgb:4B5968'
declare-option str t4 'rgb:8792AB'
declare-option str t5 'rgb:6F91BC'
declare-option str t6 'rgb:8BB2B9'
declare-option str t7 'rgb:EEAC90'
declare-option str t8 'rgb:B0BD9F'
declare-option str t9 'rgb:B3CCD0'
declare-option str t10 'rgb:B0D4D8'
declare-option str t11 'rgb:FFBF52'
declare-option str highlight 'rgb:FF0A50'
declare-option str highlight_two 'rgb:0AFFA9'
declare-option str highlight_three 'rgb:F8ED8B'
declare-option str black 'rgb:000000'
declare-option str selection 'rgb:382E1E'
declare-option str comment 'rgb:61BDD1'
declare-option str comment_doc 'rgb:234048'
declare-option str error 'rgb:FF0900'
declare-option str warning 'rgb:FFBF00'
declare-option str display 'rgb:57FF89'
declare-option str info 'rgb:DAD7D5'
set-face global ts_comment "%opt{comment}+F"
set-face global ts_constant "%opt{t11}+F"
set-face global ts_function "%opt{t10}+F"
set-face global ts_function_method "%opt{t10}+F"
set-face global ts_function_macro "%opt{t7}+F"
set-face global ts_keyword_storage_modifier "%opt{t7}+F"
set-face global ts_keyword_control_import "%opt{t8}+F"
set-face global ts_keyword_control "%opt{t8}+F"
set-face global ts_keyword_function "%opt{t7}+F"
set-face global ts_keyword "%opt{t6}+F"
set-face global ts_operator "%opt{t8}+F"
set-face global ts_punctuation "%opt{t9}+F"
set-face global ts_string "%opt{t6}+Fi"
set-face global ts_string_regexp "%opt{t6}+F"
set-face global ts_tag "%opt{t4}+F"
set-face global ts_type "%opt{t8}+Fb"
set-face global ts_namespace "%opt{t6}+Fb"
set-face global ts_variable "%opt{t4}+F"
set-face global ts_label "%opt{t4}+F"
set-face global ts_diff_plus "%opt{diff_plus}+F"
set-face global ts_diff_delta "%opt{diff_delta}+F"
set-face global ts_diff_delta_moved "%opt{diff_delta_moved}+F"
set-face global ts_diff_minus "%opt{diff_minus}+F"
set-face global ts_special "%opt{t7}+Fb"
set-face global ts_markup_heading "%opt{t4}+F"
set-face global ts_markup_bold "%opt{t4}+F"
set-face global ts_markup_italic "%opt{t4}+F"
set-face global ts_markup_strikethrough "%opt{t4}+Fs"
set-face global ts_markup_link_url "%opt{t4}+Fu"
set-face global ts_markup_link_text "%opt{t4}+F"
set-face global ts_markup_quote "%opt{t4}+F"
set-face global ts_markup_raw "%opt{t4}+F"